name: Transhumanism
markdown: redcarpet
highlighter: pygments
description: "The Singularity is Weird"
baseurl: '/hplus'
tracking_id: UA-40241848-1
tracking_property: qrohlf.com
github_repo: qrohlf/hplus